### ISSUE TITLE
Duplicate tag "User" in file ollama-chat.nvim.txt

### ISSUE THREAD

**Issue by MartinDelille** [gerazov/ollama-chat.nvim#3]
I have the following error when trying to install the plugin using [lazy.nvim](https://github.com/folke/lazy.nvim):

```
~/.local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/task/plugin.lua:84: Vim:E154:
Duplicate tag "User" in file /Users/martindelille/.local/share/nvim/lazy/ollama-chat.nvim/doc//ollama-chat.nvim.txt
```

It then appear installed and loaded but command don't work:

```
E492: Not an editor command: OllamaChat
```

**Comment by gerazov** [comment]
Seems the help documentation treats `*User*` as a tag and it appears multiple times.

Deleted all *User* instances with [6fe0fc0](https://github.com/gerazov/ollama-chat.nvim/commit/6fe0fc05eecef7d3dc1377eac6d745d1d08ce933) - it works on my side, please check.

**Comment by MartinDelille** [comment]
It fixed both the error and the editor command. Thanks!
